// File generated by flutterfire_cli.
// This file should be version controlled and should not be manually edited.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: 'YOUR_WEB_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'opas-agriculture',
    authDomain: 'opas-agriculture.firebaseapp.com',
    storageBucket: 'opas-agriculture.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCcIR98eUySyZQq_5sIYCSCeOUjD9826o',
    appId: '1:260054441220:android:2fdce00e7318849f794451',
    messagingSenderId: '260054441220',
    projectId: 'opas-mobile-app',
    storageBucket: 'opas-mobile-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCcIR98eUySyZQq_5sIYCSCeOUjD9826o',
    appId: '1:260054441220:ios:2fdce00e7318849f794451',
    messagingSenderId: '260054441220',
    projectId: 'opas-mobile-app',
    storageBucket: 'opas-mobile-app.firebasestorage.app',
    iosBundleId: 'com.opas.agriculture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCcIR98eUySyZQq_5sIYCSCeOUjD9826o',
    appId: '1:260054441220:ios:2fdce00e7318849f794451',
    messagingSenderId: '260054441220',
    projectId: 'opas-mobile-app',
    storageBucket: 'opas-mobile-app.firebasestorage.app',
    iosBundleId: 'com.opas.agriculture',
  );
}
