# Generated by Django 4.2.1 on 2025-11-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_seller_management_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_seller_approved',
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Account creation timestamp'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('BUYER', 'Buyer'), ('SELLER', 'Seller'), ('OPAS_ADMIN', 'OPAS Admin'), ('SYSTEM_ADMIN', 'System Admin')], default='BUYER', help_text='User role: Buyer, Seller, Admin, or System Admin', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='seller_approval_date',
            field=models.DateTimeField(blank=True, help_text='Date when seller was approved', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='seller_documents_verified',
            field=models.BooleanField(default=False, help_text='Whether seller documents have been verified by admin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='seller_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('SUSPENDED', 'Suspended'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Current approval status for seller applications', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='store_description',
            field=models.TextField(blank=True, help_text="Description of the seller's store/business", null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='store_name',
            field=models.CharField(blank=True, help_text="Name of the seller's store/business", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='suspended_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when account was suspended', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='suspension_reason',
            field=models.TextField(blank=True, help_text='Reason for account suspension (if applicable)', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='users_phone_n_a3b1c5_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_role_0ace22_idx'),
        ),
    ]
