# Generated by Django 4.2.1 on 2025-11-18 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(help_text='Name of the farm', max_length=255)),
                ('farm_location', models.CharField(help_text='Location/address of the farm', max_length=255)),
                ('store_name', models.CharField(help_text="Name of the seller's store/business", max_length=255)),
                ('store_description', models.TextField(help_text="Description of the seller's store/business")),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Current application status', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (if rejected)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the application was submitted')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the application was last updated')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the application was reviewed', null=True)),
            ],
            options={
                'verbose_name': 'Seller Application',
                'verbose_name_plural': 'Seller Applications',
                'ordering': ['-created_at'],
            },
        ),
        # migrations.RenameIndex(
        #     model_name='user',
        #     new_name='users_seller__de5ed3_idx',
        #     old_name='seller_status_idx',
        # ),
        migrations.AddField(
            model_name='sellerapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='The admin who reviewed this application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='user',
            field=models.OneToOneField(help_text='The user applying to become a seller', on_delete=django.db.models.deletion.CASCADE, related_name='seller_application', to=settings.AUTH_USER_MODEL),
        ),
    ]
