# Generated by Django 4.2.1 on 2025-11-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_notifications_announcements'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerforecast',
            name='average_daily_sales',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Average daily sales from historical data', max_digits=10),
        ),
        migrations.AddField(
            model_name='sellerforecast',
            name='growth_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Growth rate percentage (-100% to +100%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='sellerforecast',
            name='historical_sales_count',
            field=models.IntegerField(default=0, help_text='Number of historical data points used'),
        ),
        migrations.AddField(
            model_name='sellerforecast',
            name='recommendations',
            field=models.JSONField(blank=True, default=list, help_text='List of actionable recommendations'),
        ),
        migrations.AddField(
            model_name='sellerforecast',
            name='seasonality_detected',
            field=models.BooleanField(default=False, help_text='Whether seasonality pattern was detected'),
        ),
        migrations.AddField(
            model_name='sellerforecast',
            name='trend',
            field=models.CharField(choices=[('UPTREND', 'Uptrend'), ('DOWNTREND', 'Downtrend'), ('STABLE', 'Stable')], default='STABLE', help_text='Demand trend (uptrend, downtrend, stable)', max_length=20),
        ),
        migrations.AddField(
            model_name='sellerforecast',
            name='trend_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Trend adjustment multiplier', max_digits=5),
        ),
        migrations.AddField(
            model_name='sellerforecast',
            name='volatility',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sales volatility percentage (0-100%)', max_digits=5),
        ),
    ]
