# Generated by Django 4.2.1 on 2025-11-19 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0009_sellerforecast_enhanced_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(help_text='Type of action performed', max_length=100)),
                ('action_category', models.CharField(choices=[('SELLER_APPROVAL', 'Seller Approval'), ('SELLER_SUSPENSION', 'Seller Suspension'), ('PRICE_UPDATE', 'Price Update'), ('OPAS_REVIEW', 'OPAS Submission Review'), ('INVENTORY_ADJUSTMENT', 'Inventory Adjustment'), ('ADVISORY_CREATED', 'Advisory Created'), ('ALERT_ISSUED', 'Alert Issued'), ('ANNOUNCEMENT', 'Announcement'), ('OTHER', 'Other')], help_text='Category of action', max_length=50)),
                ('description', models.TextField(help_text='Description of the action')),
                ('old_value', models.TextField(blank=True, help_text='Previous value (before change)', null=True)),
                ('new_value', models.TextField(blank=True, help_text='New value (after change)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the action was performed')),
            ],
            options={
                'verbose_name': 'Admin Audit Log',
                'verbose_name_plural': 'Admin Audit Logs',
                'db_table': 'admin_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('SELLER_MANAGER', 'Seller Manager'), ('PRICE_MANAGER', 'Price Manager'), ('OPAS_MANAGER', 'OPAS Manager'), ('ANALYTICS_MANAGER', 'Analytics Manager'), ('SUPPORT_ADMIN', 'Support Admin')], default='SELLER_MANAGER', help_text='Admin role hierarchy for permission levels', max_length=30)),
                ('department', models.CharField(blank=True, help_text='Department/team assignment (e.g., Seller Onboarding, Market Regulation)', max_length=100, null=True)),
                ('last_login', models.DateTimeField(blank=True, help_text='Last successful login timestamp', null=True)),
                ('last_activity', models.DateTimeField(blank=True, help_text='Last recorded activity timestamp', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this admin account is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the admin account was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the admin profile was last updated')),
            ],
            options={
                'verbose_name': 'Admin User',
                'verbose_name_plural': 'Admin Users',
                'db_table': 'admin_users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Alert title', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the alert')),
                ('alert_type', models.CharField(choices=[('PRICE_VIOLATION', 'Price Violation'), ('SELLER_ISSUE', 'Seller Issue'), ('INVENTORY_ALERT', 'Inventory Alert'), ('UNUSUAL_ACTIVITY', 'Unusual Activity'), ('COMPLIANCE', 'Compliance Issue')], help_text='Type of alert', max_length=50)),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='WARNING', help_text='Alert severity level', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], default='OPEN', help_text='Alert status', max_length=20)),
                ('resolution_notes', models.TextField(blank=True, help_text='How the alert was resolved', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When alert was created')),
                ('acknowledged_at', models.DateTimeField(blank=True, help_text='When alert was acknowledged', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When alert was resolved', null=True)),
            ],
            options={
                'verbose_name': 'Marketplace Alert',
                'verbose_name_plural': 'Marketplace Alerts',
                'db_table': 'marketplace_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OPASInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.IntegerField(help_text='Total quantity received into OPAS inventory')),
                ('quantity_on_hand', models.IntegerField(help_text='Current quantity available')),
                ('quantity_consumed', models.IntegerField(default=0, help_text='Quantity consumed/sold out')),
                ('quantity_spoiled', models.IntegerField(default=0, help_text='Quantity spoiled/damaged')),
                ('storage_location', models.CharField(blank=True, help_text='Storage location/warehouse', max_length=255, null=True)),
                ('storage_condition', models.CharField(choices=[('AMBIENT', 'Ambient'), ('COLD_CHAIN', 'Cold Chain'), ('REFRIGERATED', 'Refrigerated')], default='AMBIENT', help_text='Storage condition required', max_length=50)),
                ('received_at', models.DateTimeField(auto_now_add=True, help_text='When inventory was received')),
                ('in_date', models.DateTimeField(help_text='Manufactured/production date')),
                ('expiry_date', models.DateTimeField(help_text='Expiration date of the produce')),
                ('low_stock_threshold', models.IntegerField(default=0, help_text='Quantity threshold for low stock alert')),
                ('is_low_stock', models.BooleanField(default=False, help_text='Whether current stock is below threshold')),
                ('is_expiring', models.BooleanField(default=False, help_text='Whether produce is expiring within 7 days')),
            ],
            options={
                'verbose_name': 'OPAS Inventory',
                'verbose_name_plural': 'OPAS Inventory',
                'db_table': 'opas_inventory',
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='OPASInventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('IN', 'Stock In (Purchase)'), ('OUT', 'Stock Out (Consumption/Sale)'), ('ADJUSTMENT', 'Inventory Adjustment'), ('RETURN', 'Return'), ('SPOILAGE', 'Spoilage')], help_text='Type of transaction', max_length=20)),
                ('quantity', models.IntegerField(help_text='Quantity in this transaction')),
                ('reference_number', models.CharField(blank=True, help_text='Reference number (PO, invoice, etc.)', max_length=100, null=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for transaction (especially for adjustments/spoilage)', null=True)),
                ('is_fifo_compliant', models.BooleanField(default=True, help_text='Whether this transaction follows FIFO')),
                ('batch_id', models.CharField(blank=True, help_text='Batch ID for FIFO tracking', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When transaction was recorded')),
            ],
            options={
                'verbose_name': 'OPAS Inventory Transaction',
                'verbose_name_plural': 'OPAS Inventory Transactions',
                'db_table': 'opas_inventory_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OPASPurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Quantity purchased')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total purchase price', max_digits=12)),
                ('quality_grade', models.CharField(help_text='Quality grade of product', max_length=20)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('PARTIAL', 'Partial')], default='PENDING', help_text='Payment status', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, help_text='When payment was made', null=True)),
                ('purchased_at', models.DateTimeField(auto_now_add=True, help_text='When purchase was completed')),
            ],
            options={
                'verbose_name': 'OPAS Purchase History',
                'verbose_name_plural': 'OPAS Purchase History',
                'db_table': 'opas_purchase_history',
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='OPASPurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PARTIALLY_APPROVED', 'Partially Approved'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Review status of OPAS submission', max_length=25)),
                ('offered_quantity', models.IntegerField(help_text='Quantity offered by seller')),
                ('offered_price', models.DecimalField(decimal_places=2, help_text='Price per unit offered by seller', max_digits=10)),
                ('approved_quantity', models.IntegerField(blank=True, help_text='Quantity approved by admin', null=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, help_text='Final price per unit set by admin', max_digits=10, null=True)),
                ('quality_grade', models.CharField(blank=True, choices=[('PREMIUM', 'Premium'), ('GRADE_A', 'Grade A'), ('GRADE_B', 'Grade B'), ('STANDARD', 'Standard')], help_text='Quality assessment', max_length=20, null=True)),
                ('delivery_terms', models.TextField(blank=True, help_text='Delivery terms and schedule', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin review notes', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (if rejected)', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='When offer was submitted')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When admin reviewed offer', null=True)),
                ('approved_at', models.DateTimeField(blank=True, help_text='When offer was approved', null=True)),
            ],
            options={
                'verbose_name': 'OPAS Purchase Order',
                'verbose_name_plural': 'OPAS Purchase Orders',
                'db_table': 'opas_purchase_orders',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceAdvisory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Advisory title', max_length=255)),
                ('content', models.TextField(help_text='Advisory content/message')),
                ('advisory_type', models.CharField(choices=[('PRICE_UPDATE', 'Price Update'), ('SHORTAGE_ALERT', 'Shortage Alert'), ('PROMOTION', 'Promotion'), ('MARKET_TREND', 'Market Trend')], help_text='Type of advisory', max_length=50)),
                ('target_audience', models.CharField(choices=[('ALL', 'All Users'), ('BUYERS', 'Buyers Only'), ('SELLERS', 'Sellers Only'), ('SPECIFIC', 'Specific Users')], default='ALL', help_text='Who this advisory is targeted to', max_length=50)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now, help_text='When advisory becomes visible')),
                ('effective_until', models.DateTimeField(blank=True, help_text='When advisory expires', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether advisory is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the advisory was created')),
            ],
            options={
                'verbose_name': 'Price Advisory',
                'verbose_name_plural': 'Price Advisories',
                'db_table': 'price_advisories',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='PriceCeiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceiling_price', models.DecimalField(decimal_places=2, help_text='Maximum allowed price per unit', max_digits=10)),
                ('previous_ceiling', models.DecimalField(blank=True, decimal_places=2, help_text='Previous ceiling price for history tracking', max_digits=10, null=True)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now, help_text='When this ceiling price becomes effective')),
                ('effective_until', models.DateTimeField(blank=True, help_text='When this ceiling price expires (if temporary)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the ceiling was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the ceiling was last updated')),
            ],
            options={
                'verbose_name': 'Price Ceiling',
                'verbose_name_plural': 'Price Ceilings',
                'db_table': 'price_ceilings',
                'ordering': ['product__name'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, help_text='Previous ceiling price', max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=2, help_text='New ceiling price', max_digits=10)),
                ('change_reason', models.CharField(choices=[('MARKET_ADJUSTMENT', 'Market Adjustment'), ('FORECAST_UPDATE', 'Forecast Update'), ('COMPLIANCE', 'Compliance'), ('SEASONAL', 'Seasonal Adjustment'), ('OTHER', 'Other')], help_text='Reason for the price change', max_length=30)),
                ('reason_notes', models.TextField(blank=True, help_text='Additional notes about the price change', null=True)),
                ('affected_sellers_count', models.IntegerField(default=0, help_text='Number of sellers affected by this change')),
                ('non_compliant_count', models.IntegerField(default=0, help_text='Number of sellers now non-compliant with new ceiling')),
                ('changed_at', models.DateTimeField(auto_now_add=True, help_text='When the price was changed')),
            ],
            options={
                'verbose_name': 'Price History',
                'verbose_name_plural': 'Price History',
                'db_table': 'price_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceNonCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listed_price', models.DecimalField(decimal_places=2, help_text='The price listed by seller', max_digits=10)),
                ('ceiling_price', models.DecimalField(decimal_places=2, help_text='The ceiling price at time of violation', max_digits=10)),
                ('overage_percentage', models.DecimalField(decimal_places=2, help_text='Percentage over ceiling', max_digits=5)),
                ('status', models.CharField(choices=[('NEW', 'New Violation'), ('WARNED', 'Warning Issued'), ('ADJUSTED', 'Price Adjusted'), ('SUSPENDED', 'Seller Suspended'), ('RESOLVED', 'Resolved')], default='NEW', help_text='Current status of violation', max_length=20)),
                ('warning_issued_at', models.DateTimeField(blank=True, help_text='When warning was issued', null=True)),
                ('warning_expires_at', models.DateTimeField(blank=True, help_text='When seller must comply by', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When violation was resolved', null=True)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes on how violation was resolved', null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True, help_text='When violation was first detected')),
            ],
            options={
                'verbose_name': 'Price Non-Compliance',
                'verbose_name_plural': 'Price Non-Compliances',
                'db_table': 'price_non_compliances',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended'), ('REACTIVATED', 'Reactivated')], help_text='The approval decision', max_length=20)),
                ('decision_reason', models.TextField(help_text='Reason for the decision')),
                ('admin_notes', models.TextField(blank=True, help_text='Additional admin notes', null=True)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when the decision becomes effective')),
                ('effective_until', models.DateTimeField(blank=True, help_text='Date when the decision expires (e.g., suspension end date)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the decision was recorded')),
            ],
            options={
                'verbose_name': 'Seller Approval History',
                'verbose_name_plural': 'Seller Approval History',
                'db_table': 'seller_approval_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerDocumentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(help_text='Type of document (e.g., Business Registration, Tax ID, etc.)', max_length=100)),
                ('document_url', models.URLField(help_text='URL to the document file stored in cloud storage')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', help_text='Verification status of the document', max_length=20)),
                ('verification_notes', models.TextField(blank=True, help_text='Notes from admin verification', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When the document was uploaded')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When the document was verified', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the document expires (if applicable)', null=True)),
            ],
            options={
                'verbose_name': 'Seller Document Verification',
                'verbose_name_plural': 'Seller Document Verifications',
                'db_table': 'seller_document_verifications',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended'), ('REQUEST_MORE_INFO', 'More Info Requested')], default='PENDING', help_text='Current status of seller registration', max_length=20)),
                ('farm_name', models.CharField(help_text='Name of the farm', max_length=255)),
                ('farm_location', models.CharField(help_text='Location/address of the farm', max_length=255)),
                ('farm_size', models.CharField(blank=True, help_text='Size of farm (e.g., "5 hectares")', max_length=100, null=True)),
                ('products_grown', models.TextField(blank=True, help_text='List of products grown/produced', null=True)),
                ('store_name', models.CharField(help_text='Name of the store/business', max_length=255)),
                ('store_description', models.TextField(help_text='Description of the store')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='When the application was submitted')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the application was reviewed', null=True)),
                ('approved_at', models.DateTimeField(blank=True, help_text='When the application was approved', null=True)),
                ('rejected_at', models.DateTimeField(blank=True, help_text='When the application was rejected', null=True)),
            ],
            options={
                'verbose_name': 'Seller Registration Request',
                'verbose_name_plural': 'Seller Registration Requests',
                'db_table': 'seller_registration_requests',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerSuspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Reason for suspension')),
                ('severity', models.CharField(choices=[('TEMPORARY', 'Temporary'), ('PERMANENT', 'Permanent')], default='TEMPORARY', help_text='Whether suspension is temporary or permanent', max_length=20)),
                ('suspended_at', models.DateTimeField(auto_now_add=True, help_text='When the suspension was issued')),
                ('suspended_until', models.DateTimeField(blank=True, help_text='When temporary suspension expires', null=True)),
                ('lifted_at', models.DateTimeField(blank=True, help_text='When suspension was lifted/overturned', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether suspension is currently in effect')),
            ],
            options={
                'verbose_name': 'Seller Suspension',
                'verbose_name_plural': 'Seller Suspensions',
                'db_table': 'seller_suspensions',
                'ordering': ['-suspended_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Notification title', max_length=255)),
                ('message', models.TextField(help_text='Notification message')),
                ('notification_type', models.CharField(choices=[('PRICE_VIOLATION', 'Price Violation'), ('SELLER_SUSPENSION', 'Seller Suspension'), ('OPAS_PENDING', 'OPAS Pending Review'), ('INVENTORY_ALERT', 'Inventory Alert'), ('SYSTEM_ALERT', 'System Alert'), ('COMPLIANCE', 'Compliance Alert')], help_text='Type of notification', max_length=50)),
                ('is_read', models.BooleanField(default=False, help_text='Whether notification has been read')),
                ('read_at', models.DateTimeField(blank=True, help_text='When notification was read', null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', help_text='Notification priority', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When notification was created')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When notification expires', null=True)),
            ],
            options={
                'verbose_name': 'System Notification',
                'verbose_name_plural': 'System Notifications',
                'db_table': 'system_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='announcement',
            name='seller_annc_expiry_idx',
        ),
        migrations.RemoveIndex(
            model_name='announcement',
            name='seller_annc_priority_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='seller_notif_seller_idx2',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='seller_notif_type_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='seller_noti_seller__7caf50_idx',
            old_name='seller_notif_seller_idx1',
        ),
        migrations.RenameIndex(
            model_name='productimage',
            new_name='seller_prod_product_a17487_idx',
            old_name='seller_pro_product_idx1',
        ),
        migrations.RenameIndex(
            model_name='productimage',
            new_name='seller_prod_product_a6263b_idx',
            old_name='seller_pro_product_idx2',
        ),
        migrations.RenameIndex(
            model_name='sellerforecast',
            new_name='seller_fore_seller__8cfcf2_idx',
            old_name='seller_for_seller_forecast_date_idx',
        ),
        migrations.RenameIndex(
            model_name='sellerforecast',
            new_name='seller_fore_product_d88e38_idx',
            old_name='seller_for_product_forecast_date_idx',
        ),
        migrations.RenameIndex(
            model_name='sellerorder',
            new_name='seller_orde_seller__e18f13_idx',
            old_name='seller_ord_seller_status_idx',
        ),
        migrations.RenameIndex(
            model_name='sellerorder',
            new_name='seller_orde_buyer_i_0d152c_idx',
            old_name='seller_ord_buyer_status_idx',
        ),
        migrations.RenameIndex(
            model_name='sellerorder',
            new_name='seller_orde_order_n_24b1b9_idx',
            old_name='seller_ord_order_number_idx',
        ),
        migrations.RenameIndex(
            model_name='sellerpayout',
            new_name='seller_payo_seller__63d840_idx',
            old_name='seller_pay_seller_status_idx',
        ),
        migrations.RenameIndex(
            model_name='sellerpayout',
            new_name='seller_payo_period__f31d84_idx',
            old_name='seller_pay_period_end_idx',
        ),
        migrations.RenameIndex(
            model_name='sellerproduct',
            new_name='seller_prod_seller__07d9a6_idx',
            old_name='seller_pro_seller_status_idx',
        ),
        migrations.RenameIndex(
            model_name='sellerproduct',
            new_name='seller_prod_product_87eea1_idx',
            old_name='seller_pro_product_type_idx',
        ),
        migrations.RenameIndex(
            model_name='sellerproduct',
            new_name='seller_prod_expiry__323917_idx',
            old_name='seller_pro_expiry_date_idx',
        ),
        migrations.RenameIndex(
            model_name='selltoopas',
            new_name='seller_sell_seller__b94157_idx',
            old_name='seller_sell_seller_status_idx',
        ),
        migrations.RenameIndex(
            model_name='selltoopas',
            new_name='seller_sell_submiss_558985_idx',
            old_name='seller_sell_submission_number_idx',
        ),
        migrations.AlterUniqueTogether(
            name='sellerannouncementread',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='sellerannouncementread',
            name='announcement',
            field=models.ForeignKey(help_text='The announcement that was read', on_delete=django.db.models.deletion.CASCADE, related_name='seller_reads', to='users.announcement'),
        ),
        migrations.AlterField(
            model_name='sellerannouncementread',
            name='read_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When announcement was read'),
        ),
        migrations.AlterField(
            model_name='sellerannouncementread',
            name='seller',
            field=models.ForeignKey(help_text='The seller who read the announcement', on_delete=django.db.models.deletion.CASCADE, related_name='announcement_reads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sellerorder',
            name='buyer',
            field=models.ForeignKey(help_text='The buyer who placed this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='sellerannouncementread',
            unique_together={('seller', 'announcement')},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['seller', '-created_at'], name='seller_noti_seller__592459_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerannouncementread',
            index=models.Index(fields=['seller', 'announcement'], name='seller_anno_seller__aed772_idx'),
        ),
        migrations.AddField(
            model_name='systemnotification',
            name='recipient',
            field=models.ForeignKey(help_text='Admin recipient of notification', on_delete=django.db.models.deletion.CASCADE, related_name='system_notifications', to='users.adminuser'),
        ),
        migrations.AddField(
            model_name='systemnotification',
            name='related_product',
            field=models.ForeignKey(blank=True, help_text='Product this notification is about', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='users.sellerproduct'),
        ),
        migrations.AddField(
            model_name='systemnotification',
            name='related_seller',
            field=models.ForeignKey(blank=True, help_text='Seller this notification is about', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_about', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellersuspension',
            name='admin',
            field=models.ForeignKey(blank=True, help_text='The admin who issued the suspension', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_suspensions', to='users.adminuser'),
        ),
        migrations.AddField(
            model_name='sellersuspension',
            name='seller',
            field=models.ForeignKey(help_text='The suspended seller', on_delete=django.db.models.deletion.CASCADE, related_name='suspensions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellerregistrationrequest',
            name='seller',
            field=models.OneToOneField(help_text='The seller user applying for marketplace access', on_delete=django.db.models.deletion.CASCADE, related_name='registration_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellerdocumentverification',
            name='registration_request',
            field=models.ForeignKey(help_text='The seller registration request', on_delete=django.db.models.deletion.CASCADE, related_name='document_verifications', to='users.sellerregistrationrequest'),
        ),
        migrations.AddField(
            model_name='sellerdocumentverification',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='The admin who verified this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to='users.adminuser'),
        ),
        migrations.AddField(
            model_name='sellerapprovalhistory',
            name='admin',
            field=models.ForeignKey(blank=True, help_text='The admin who made the decision', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_approvals', to='users.adminuser'),
        ),
        migrations.AddField(
            model_name='sellerapprovalhistory',
            name='seller',
            field=models.ForeignKey(help_text='The seller user', on_delete=django.db.models.deletion.CASCADE, related_name='approval_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricenoncompliance',
            name='detected_by',
            field=models.ForeignKey(blank=True, help_text='The admin who detected or flagged this violation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detected_violations', to='users.adminuser'),
        ),
        migrations.AddField(
            model_name='pricenoncompliance',
            name='product',
            field=models.ForeignKey(help_text='The product with non-compliant price', on_delete=django.db.models.deletion.CASCADE, related_name='compliance_violations', to='users.sellerproduct'),
        ),
        migrations.AddField(
            model_name='pricenoncompliance',
            name='seller',
            field=models.ForeignKey(help_text='The seller with non-compliant price', on_delete=django.db.models.deletion.CASCADE, related_name='price_violations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='admin',
            field=models.ForeignKey(blank=True, help_text='The admin who made the price change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_changes', to='users.adminuser'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='product',
            field=models.ForeignKey(help_text='The product this price change applies to', on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='users.sellerproduct'),
        ),
        migrations.AddField(
            model_name='priceceiling',
            name='product',
            field=models.OneToOneField(help_text='The product this ceiling applies to', on_delete=django.db.models.deletion.CASCADE, related_name='price_ceiling', to='users.sellerproduct'),
        ),
        migrations.AddField(
            model_name='priceceiling',
            name='set_by',
            field=models.ForeignKey(blank=True, help_text='The admin who set this ceiling', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_price_ceilings', to='users.adminuser'),
        ),
        migrations.AddField(
            model_name='priceadvisory',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The admin who created this advisory', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_advisories', to='users.adminuser'),
        ),
        migrations.AddField(
            model_name='opaspurchaseorder',
            name='product',
            field=models.ForeignKey(help_text='The product offered', on_delete=django.db.models.deletion.CASCADE, related_name='opas_purchase_orders', to='users.sellerproduct'),
        ),
        migrations.AddField(
            model_name='opaspurchaseorder',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='The admin who reviewed this submission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_opas_orders', to='users.adminuser'),
        ),
        migrations.AddField(
            model_name='opaspurchaseorder',
            name='sell_to_opas',
            field=models.OneToOneField(help_text='The original OPAS submission', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order', to='users.selltoopas'),
        ),
        migrations.AddField(
            model_name='opaspurchaseorder',
            name='seller',
            field=models.ForeignKey(help_text='The seller submitting the offer', on_delete=django.db.models.deletion.CASCADE, related_name='opas_purchase_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opaspurchasehistory',
            name='product',
            field=models.ForeignKey(help_text='The product purchased', on_delete=django.db.models.deletion.CASCADE, related_name='opas_sales_history', to='users.sellerproduct'),
        ),
        migrations.AddField(
            model_name='opaspurchasehistory',
            name='purchase_order',
            field=models.ForeignKey(help_text='The purchase order', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_history', to='users.opaspurchaseorder'),
        ),
        migrations.AddField(
            model_name='opaspurchasehistory',
            name='seller',
            field=models.ForeignKey(help_text='The seller', on_delete=django.db.models.deletion.CASCADE, related_name='opas_sales_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opasinventorytransaction',
            name='inventory',
            field=models.ForeignKey(help_text='The inventory being transacted', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.opasinventory'),
        ),
        migrations.AddField(
            model_name='opasinventorytransaction',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='The admin who processed this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='users.adminuser'),
        ),
        migrations.AddField(
            model_name='opasinventory',
            name='product',
            field=models.ForeignKey(help_text='The product in OPAS inventory', on_delete=django.db.models.deletion.CASCADE, related_name='opas_inventory', to='users.sellerproduct'),
        ),
        migrations.AddField(
            model_name='opasinventory',
            name='purchase_order',
            field=models.OneToOneField(blank=True, help_text='The OPAS purchase order that created this inventory', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_entry', to='users.opaspurchaseorder'),
        ),
        migrations.AddField(
            model_name='marketplacealert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, help_text='Admin who acknowledged this alert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to='users.adminuser'),
        ),
        migrations.AddField(
            model_name='marketplacealert',
            name='affected_product',
            field=models.ForeignKey(blank=True, help_text='Product this alert is about', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_alerts', to='users.sellerproduct'),
        ),
        migrations.AddField(
            model_name='marketplacealert',
            name='affected_seller',
            field=models.ForeignKey(blank=True, help_text='Seller this alert is about', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='custom_permissions',
            field=models.ManyToManyField(blank=True, help_text='Custom permissions beyond role', related_name='admin_users', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='user',
            field=models.OneToOneField(help_text='The user with admin role', on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminauditlog',
            name='admin',
            field=models.ForeignKey(blank=True, help_text='The admin who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='users.adminuser'),
        ),
        migrations.AddField(
            model_name='adminauditlog',
            name='affected_product',
            field=models.ForeignKey(blank=True, help_text='Product affected by this action (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='users.sellerproduct'),
        ),
        migrations.AddField(
            model_name='adminauditlog',
            name='affected_seller',
            field=models.ForeignKey(blank=True, help_text='Seller affected by this action (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_as_subject', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='sellerannouncementread',
            name='is_read',
        ),
        migrations.AddIndex(
            model_name='systemnotification',
            index=models.Index(fields=['recipient_id'], name='system_noti_recipie_07d9d7_idx'),
        ),
        migrations.AddIndex(
            model_name='systemnotification',
            index=models.Index(fields=['is_read'], name='system_noti_is_read_663079_idx'),
        ),
        migrations.AddIndex(
            model_name='systemnotification',
            index=models.Index(fields=['priority'], name='system_noti_priorit_bd307b_idx'),
        ),
        migrations.AddIndex(
            model_name='systemnotification',
            index=models.Index(fields=['created_at'], name='system_noti_created_951b8e_idx'),
        ),
        migrations.AddIndex(
            model_name='systemnotification',
            index=models.Index(fields=['notification_type'], name='system_noti_notific_4933ed_idx'),
        ),
        migrations.AddIndex(
            model_name='sellersuspension',
            index=models.Index(fields=['seller_id'], name='seller_susp_seller__0470b9_idx'),
        ),
        migrations.AddIndex(
            model_name='sellersuspension',
            index=models.Index(fields=['is_active'], name='seller_susp_is_acti_e4e8b4_idx'),
        ),
        migrations.AddIndex(
            model_name='sellersuspension',
            index=models.Index(fields=['suspended_at'], name='seller_susp_suspend_7863ca_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerregistrationrequest',
            index=models.Index(fields=['seller_id'], name='seller_regi_seller__9c8c08_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerregistrationrequest',
            index=models.Index(fields=['status'], name='seller_regi_status_2bf8a5_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerregistrationrequest',
            index=models.Index(fields=['submitted_at'], name='seller_regi_submitt_b4fcf3_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerdocumentverification',
            index=models.Index(fields=['registration_request_id'], name='seller_docu_registr_6a7363_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerdocumentverification',
            index=models.Index(fields=['status'], name='seller_docu_status_7a8332_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerdocumentverification',
            index=models.Index(fields=['document_type'], name='seller_docu_documen_4d7987_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sellerdocumentverification',
            unique_together={('registration_request', 'document_type')},
        ),
        migrations.AddIndex(
            model_name='sellerapprovalhistory',
            index=models.Index(fields=['seller_id'], name='seller_appr_seller__f20bb4_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerapprovalhistory',
            index=models.Index(fields=['decision'], name='seller_appr_decisio_24ddaf_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerapprovalhistory',
            index=models.Index(fields=['created_at'], name='seller_appr_created_4f502e_idx'),
        ),
        migrations.AddIndex(
            model_name='pricenoncompliance',
            index=models.Index(fields=['seller_id'], name='price_non_c_seller__63049d_idx'),
        ),
        migrations.AddIndex(
            model_name='pricenoncompliance',
            index=models.Index(fields=['product_id'], name='price_non_c_product_4adf78_idx'),
        ),
        migrations.AddIndex(
            model_name='pricenoncompliance',
            index=models.Index(fields=['status'], name='price_non_c_status_28c837_idx'),
        ),
        migrations.AddIndex(
            model_name='pricenoncompliance',
            index=models.Index(fields=['detected_at'], name='price_non_c_detecte_4d0944_idx'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['product_id'], name='price_histo_product_68985b_idx'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['changed_at'], name='price_histo_changed_4c8483_idx'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['change_reason'], name='price_histo_change__06aaa3_idx'),
        ),
        migrations.AddIndex(
            model_name='priceceiling',
            index=models.Index(fields=['product_id'], name='price_ceili_product_797590_idx'),
        ),
        migrations.AddIndex(
            model_name='priceceiling',
            index=models.Index(fields=['effective_from'], name='price_ceili_effecti_5d03ed_idx'),
        ),
        migrations.AddIndex(
            model_name='priceadvisory',
            index=models.Index(fields=['is_active'], name='price_advis_is_acti_294b32_idx'),
        ),
        migrations.AddIndex(
            model_name='priceadvisory',
            index=models.Index(fields=['effective_from'], name='price_advis_effecti_c290a9_idx'),
        ),
        migrations.AddIndex(
            model_name='priceadvisory',
            index=models.Index(fields=['advisory_type'], name='price_advis_advisor_f1ee41_idx'),
        ),
        migrations.AddIndex(
            model_name='opaspurchaseorder',
            index=models.Index(fields=['seller_id'], name='opas_purcha_seller__3b2cb4_idx'),
        ),
        migrations.AddIndex(
            model_name='opaspurchaseorder',
            index=models.Index(fields=['product_id'], name='opas_purcha_product_787ffa_idx'),
        ),
        migrations.AddIndex(
            model_name='opaspurchaseorder',
            index=models.Index(fields=['status'], name='opas_purcha_status_6e2622_idx'),
        ),
        migrations.AddIndex(
            model_name='opaspurchaseorder',
            index=models.Index(fields=['submitted_at'], name='opas_purcha_submitt_2c725b_idx'),
        ),
        migrations.AddIndex(
            model_name='opaspurchasehistory',
            index=models.Index(fields=['seller_id'], name='opas_purcha_seller__9783e2_idx'),
        ),
        migrations.AddIndex(
            model_name='opaspurchasehistory',
            index=models.Index(fields=['product_id'], name='opas_purcha_product_b0ed81_idx'),
        ),
        migrations.AddIndex(
            model_name='opaspurchasehistory',
            index=models.Index(fields=['purchased_at'], name='opas_purcha_purchas_cac369_idx'),
        ),
        migrations.AddIndex(
            model_name='opasinventorytransaction',
            index=models.Index(fields=['inventory_id'], name='opas_invent_invento_209d5d_idx'),
        ),
        migrations.AddIndex(
            model_name='opasinventorytransaction',
            index=models.Index(fields=['transaction_type'], name='opas_invent_transac_4b3307_idx'),
        ),
        migrations.AddIndex(
            model_name='opasinventorytransaction',
            index=models.Index(fields=['created_at'], name='opas_invent_created_b182bb_idx'),
        ),
        migrations.AddIndex(
            model_name='opasinventorytransaction',
            index=models.Index(fields=['batch_id'], name='opas_invent_batch_i_0e1dc4_idx'),
        ),
        migrations.AddIndex(
            model_name='opasinventory',
            index=models.Index(fields=['product_id'], name='opas_invent_product_ddfee2_idx'),
        ),
        migrations.AddIndex(
            model_name='opasinventory',
            index=models.Index(fields=['quantity_on_hand'], name='opas_invent_quantit_6ae25f_idx'),
        ),
        migrations.AddIndex(
            model_name='opasinventory',
            index=models.Index(fields=['is_low_stock'], name='opas_invent_is_low__668591_idx'),
        ),
        migrations.AddIndex(
            model_name='opasinventory',
            index=models.Index(fields=['expiry_date'], name='opas_invent_expiry__537415_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplacealert',
            index=models.Index(fields=['alert_type'], name='marketplace_alert_t_2c0602_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplacealert',
            index=models.Index(fields=['severity'], name='marketplace_severit_795474_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplacealert',
            index=models.Index(fields=['status'], name='marketplace_status_d150b5_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplacealert',
            index=models.Index(fields=['created_at'], name='marketplace_created_f9336d_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplacealert',
            index=models.Index(fields=['affected_seller_id'], name='marketplace_affecte_97eb39_idx'),
        ),
        migrations.AddIndex(
            model_name='adminuser',
            index=models.Index(fields=['admin_role'], name='admin_users_admin_r_8017bc_idx'),
        ),
        migrations.AddIndex(
            model_name='adminuser',
            index=models.Index(fields=['department'], name='admin_users_departm_50df59_idx'),
        ),
        migrations.AddIndex(
            model_name='adminuser',
            index=models.Index(fields=['is_active'], name='admin_users_is_acti_ac20ec_idx'),
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['admin_id'], name='admin_audit_admin_i_cbd562_idx'),
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['action_category'], name='admin_audit_action__d10fcf_idx'),
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['affected_seller_id'], name='admin_audit_affecte_b490b2_idx'),
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['created_at'], name='admin_audit_created_7f55c8_idx'),
        ),
    ]
