# Generated by Django 4.2.1 on 2025-11-22 06:57
# Enhanced admin models with validators, indexes, and constraints

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_adminauditlog_adminuser_marketplacealert_and_more'),
    ]

    operations = [
        # Add validators to OPASInventory fields
        migrations.AlterField(
            model_name='opasinventory',
            name='quantity_received',
            field=models.IntegerField(
                help_text='Total quantity received into OPAS inventory',
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name='opasinventory',
            name='quantity_on_hand',
            field=models.IntegerField(
                help_text='Current quantity available',
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name='opasinventory',
            name='quantity_consumed',
            field=models.IntegerField(
                default=0,
                help_text='Quantity consumed/sold out',
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name='opasinventory',
            name='quantity_spoiled',
            field=models.IntegerField(
                default=0,
                help_text='Quantity spoiled/damaged',
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name='opasinventory',
            name='low_stock_threshold',
            field=models.IntegerField(
                default=0,
                help_text='Quantity threshold for low stock alert',
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        # Add validators to PriceNonCompliance fields
        migrations.AlterField(
            model_name='pricenoncompliance',
            name='listed_price',
            field=models.DecimalField(
                decimal_places=2,
                help_text='The price listed by seller',
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name='pricenoncompliance',
            name='ceiling_price',
            field=models.DecimalField(
                decimal_places=2,
                help_text='The ceiling price at time of violation',
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name='pricenoncompliance',
            name='overage_percentage',
            field=models.DecimalField(
                decimal_places=2,
                help_text='Percentage over ceiling',
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        # Add new indexes for performance optimization
        migrations.AddIndex(
            model_name='adminuser',
            index=models.Index(fields=['user_id'], name='admin_users_user_id_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplacealert',
            index=models.Index(fields=['severity', 'status'], name='marketplace_alert_severity_status_idx'),
        ),
        migrations.AddIndex(
            model_name='opasinventory',
            index=models.Index(fields=['is_expiring'], name='opas_inventory_is_expiring_idx'),
        ),
        migrations.AddIndex(
            model_name='opasinventory',
            index=models.Index(fields=['storage_location'], name='opas_inventory_storage_location_idx'),
        ),
        migrations.AddIndex(
            model_name='pricenoncompliance',
            index=models.Index(fields=['seller_id', 'status'], name='price_non_compliance_seller_status_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerregistrationrequest',
            index=models.Index(fields=['status', 'submitted_at'], name='seller_registration_status_submitted_idx'),
        ),
        # Add constraint for data integrity
        migrations.AddConstraint(
            model_name='pricenoncompliance',
            constraint=models.CheckConstraint(
                check=models.Q(('listed_price__gt', models.F('ceiling_price'))),
                name='pricenoncompliance_listed_price_exceeds_ceiling'
            ),
        ),
    ]
