# Generated by Django 4.2.1 on 2025-11-22 15:21

import apps.users.admin_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_phase_2_1_model_completion'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pricenoncompliance',
            name='pricenoncompliance_listed_price_exceeds_ceiling',
        ),
        migrations.RenameIndex(
            model_name='adminuser',
            new_name='admin_users_user_id_8fd899_idx',
            old_name='admin_users_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='marketplacealert',
            new_name='marketplace_severit_ea2a51_idx',
            old_name='marketplace_alert_severity_status_idx',
        ),
        migrations.RenameIndex(
            model_name='opasinventory',
            new_name='opas_invent_is_expi_e0d35e_idx',
            old_name='opas_inventory_is_expiring_idx',
        ),
        migrations.RenameIndex(
            model_name='opasinventory',
            new_name='opas_invent_storage_931179_idx',
            old_name='opas_inventory_storage_location_idx',
        ),
        migrations.RenameIndex(
            model_name='pricenoncompliance',
            new_name='price_non_c_seller__19185e_idx',
            old_name='price_non_compliance_seller_status_idx',
        ),
        migrations.RenameIndex(
            model_name='sellerregistrationrequest',
            new_name='seller_regi_status_51d46a_idx',
            old_name='seller_registration_status_submitted_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_seller__de5ed3_idx',
            old_name='seller_status_idx',
        ),
        migrations.AddField(
            model_name='sellerorder',
            name='fulfillment_days',
            field=models.IntegerField(blank=True, help_text='Number of days from creation to delivery', null=True),
        ),
        migrations.AddField(
            model_name='sellerorder',
            name='on_time',
            field=models.BooleanField(default=True, help_text='Whether order was fulfilled on time'),
        ),
        migrations.AddField(
            model_name='sellerproduct',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When the product was deleted', null=True),
        ),
        migrations.AddField(
            model_name='sellerproduct',
            name='deletion_reason',
            field=models.TextField(blank=True, help_text='Reason for deletion', null=True),
        ),
        migrations.AddField(
            model_name='sellerproduct',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag for product listing'),
        ),
        migrations.AlterField(
            model_name='adminauditlog',
            name='action_type',
            field=models.CharField(help_text='Type of action performed', max_length=100, validators=[apps.users.admin_models.validate_action_type_in_valid_choices]),
        ),
        migrations.AlterField(
            model_name='priceceiling',
            name='ceiling_price',
            field=models.DecimalField(decimal_places=2, help_text='Maximum allowed price per unit', max_digits=10, validators=[apps.users.admin_models.validate_ceiling_price_positive]),
        ),
        migrations.AlterField(
            model_name='pricenoncompliance',
            name='overage_percentage',
            field=models.DecimalField(decimal_places=2, help_text='Percentage over ceiling', max_digits=5, validators=[apps.users.admin_models.validate_overage_percent_non_negative]),
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['admin_id', 'action_category'], name='admin_audit_admin_i_38016a_idx'),
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['admin_id', 'created_at'], name='admin_audit_admin_i_fe5621_idx'),
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['action_category', 'created_at'], name='admin_audit_action__72474e_idx'),
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['action_type'], name='admin_audit_action__54511b_idx'),
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['affected_product_id'], name='admin_audit_affecte_6f238f_idx'),
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['affected_seller_id', 'created_at'], name='admin_audit_affecte_45fa47_idx'),
        ),
        migrations.AddIndex(
            model_name='adminuser',
            index=models.Index(fields=['admin_role', 'is_active'], name='admin_users_admin_r_24b5c0_idx'),
        ),
        migrations.AddIndex(
            model_name='adminuser',
            index=models.Index(fields=['department', 'is_active'], name='admin_users_departm_c0d056_idx'),
        ),
        migrations.AddIndex(
            model_name='adminuser',
            index=models.Index(fields=['created_at'], name='admin_users_created_9e09db_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplacealert',
            index=models.Index(fields=['alert_type', 'severity'], name='marketplace_alert_t_78f6fa_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplacealert',
            index=models.Index(fields=['status', 'created_at'], name='marketplace_status_750479_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplacealert',
            index=models.Index(fields=['acknowledged_by_id'], name='marketplace_acknowl_284e20_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplacealert',
            index=models.Index(fields=['affected_product_id'], name='marketplace_affecte_947016_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplacealert',
            index=models.Index(fields=['severity', 'status', 'created_at'], name='marketplace_severit_324475_idx'),
        ),
        migrations.AddIndex(
            model_name='opasinventory',
            index=models.Index(fields=['product_id', 'expiry_date'], name='opas_invent_product_7baa11_idx'),
        ),
        migrations.AddIndex(
            model_name='opasinventory',
            index=models.Index(fields=['is_low_stock', 'quantity_on_hand'], name='opas_invent_is_low__b90da0_idx'),
        ),
        migrations.AddIndex(
            model_name='opasinventory',
            index=models.Index(fields=['is_expiring', 'expiry_date'], name='opas_invent_is_expi_25b804_idx'),
        ),
        migrations.AddIndex(
            model_name='opasinventory',
            index=models.Index(fields=['storage_location', 'is_low_stock'], name='opas_invent_storage_21ad2b_idx'),
        ),
        migrations.AddIndex(
            model_name='opasinventory',
            index=models.Index(fields=['received_at'], name='opas_invent_receive_ea275d_idx'),
        ),
        migrations.AddIndex(
            model_name='opasinventory',
            index=models.Index(fields=['purchase_order_id'], name='opas_invent_purchas_bebcfa_idx'),
        ),
        migrations.AddIndex(
            model_name='opasinventorytransaction',
            index=models.Index(fields=['inventory_id', 'transaction_type'], name='opas_invent_invento_d59857_idx'),
        ),
        migrations.AddIndex(
            model_name='opasinventorytransaction',
            index=models.Index(fields=['inventory_id', 'created_at'], name='opas_invent_invento_737ef0_idx'),
        ),
        migrations.AddIndex(
            model_name='opasinventorytransaction',
            index=models.Index(fields=['transaction_type', 'created_at'], name='opas_invent_transac_b5f27c_idx'),
        ),
        migrations.AddIndex(
            model_name='opasinventorytransaction',
            index=models.Index(fields=['processed_by_id'], name='opas_invent_process_540404_idx'),
        ),
        migrations.AddIndex(
            model_name='opasinventorytransaction',
            index=models.Index(fields=['is_fifo_compliant'], name='opas_invent_is_fifo_40d95e_idx'),
        ),
        migrations.AddIndex(
            model_name='opaspurchasehistory',
            index=models.Index(fields=['seller_id', 'purchased_at'], name='opas_purcha_seller__8902fd_idx'),
        ),
        migrations.AddIndex(
            model_name='opaspurchasehistory',
            index=models.Index(fields=['product_id', 'purchased_at'], name='opas_purcha_product_7c56f1_idx'),
        ),
        migrations.AddIndex(
            model_name='opaspurchasehistory',
            index=models.Index(fields=['payment_status'], name='opas_purcha_payment_b2fa3b_idx'),
        ),
        migrations.AddIndex(
            model_name='opaspurchasehistory',
            index=models.Index(fields=['purchase_order_id'], name='opas_purcha_purchas_350e6c_idx'),
        ),
        migrations.AddIndex(
            model_name='opaspurchaseorder',
            index=models.Index(fields=['seller_id', 'status'], name='opas_purcha_seller__1cc147_idx'),
        ),
        migrations.AddIndex(
            model_name='opaspurchaseorder',
            index=models.Index(fields=['status', 'submitted_at'], name='opas_purcha_status_816e8e_idx'),
        ),
        migrations.AddIndex(
            model_name='opaspurchaseorder',
            index=models.Index(fields=['reviewed_by_id'], name='opas_purcha_reviewe_73ce2a_idx'),
        ),
        migrations.AddIndex(
            model_name='opaspurchaseorder',
            index=models.Index(fields=['reviewed_at'], name='opas_purcha_reviewe_0a760f_idx'),
        ),
        migrations.AddIndex(
            model_name='opaspurchaseorder',
            index=models.Index(fields=['approved_at'], name='opas_purcha_approve_05678f_idx'),
        ),
        migrations.AddIndex(
            model_name='priceadvisory',
            index=models.Index(fields=['is_active', 'effective_from'], name='price_advis_is_acti_974d13_idx'),
        ),
        migrations.AddIndex(
            model_name='priceadvisory',
            index=models.Index(fields=['created_by_id'], name='price_advis_created_bfcfec_idx'),
        ),
        migrations.AddIndex(
            model_name='priceadvisory',
            index=models.Index(fields=['target_audience'], name='price_advis_target__6c9eed_idx'),
        ),
        migrations.AddIndex(
            model_name='priceadvisory',
            index=models.Index(fields=['effective_until'], name='price_advis_effecti_7313f1_idx'),
        ),
        migrations.AddIndex(
            model_name='priceceiling',
            index=models.Index(fields=['product_id', 'effective_from'], name='price_ceili_product_3e52ca_idx'),
        ),
        migrations.AddIndex(
            model_name='priceceiling',
            index=models.Index(fields=['set_by_id'], name='price_ceili_set_by__511bb7_idx'),
        ),
        migrations.AddIndex(
            model_name='priceceiling',
            index=models.Index(fields=['effective_until'], name='price_ceili_effecti_422957_idx'),
        ),
        migrations.AddIndex(
            model_name='priceceiling',
            index=models.Index(fields=['updated_at'], name='price_ceili_updated_56d192_idx'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['product_id', 'changed_at'], name='price_histo_product_779574_idx'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['admin_id'], name='price_histo_admin_i_770166_idx'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['change_reason', 'changed_at'], name='price_histo_change__0f7fc6_idx'),
        ),
        migrations.AddIndex(
            model_name='pricenoncompliance',
            index=models.Index(fields=['product_id', 'status'], name='price_non_c_product_5547df_idx'),
        ),
        migrations.AddIndex(
            model_name='pricenoncompliance',
            index=models.Index(fields=['seller_id', 'product_id'], name='price_non_c_seller__bb0178_idx'),
        ),
        migrations.AddIndex(
            model_name='pricenoncompliance',
            index=models.Index(fields=['status', 'detected_at'], name='price_non_c_status_849b0d_idx'),
        ),
        migrations.AddIndex(
            model_name='pricenoncompliance',
            index=models.Index(fields=['detected_by_id'], name='price_non_c_detecte_298444_idx'),
        ),
        migrations.AddIndex(
            model_name='pricenoncompliance',
            index=models.Index(fields=['warning_expires_at'], name='price_non_c_warning_7574ea_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerapprovalhistory',
            index=models.Index(fields=['seller_id', 'decision'], name='seller_appr_seller__e679c8_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerapprovalhistory',
            index=models.Index(fields=['admin_id'], name='seller_appr_admin_i_7f857b_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerapprovalhistory',
            index=models.Index(fields=['effective_from'], name='seller_appr_effecti_5a56bd_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerapprovalhistory',
            index=models.Index(fields=['decision', 'created_at'], name='seller_appr_decisio_d61fcb_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerdocumentverification',
            index=models.Index(fields=['registration_request_id', 'status'], name='seller_docu_registr_b0bd36_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerdocumentverification',
            index=models.Index(fields=['verified_by_id'], name='seller_docu_verifie_89a712_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerdocumentverification',
            index=models.Index(fields=['uploaded_at'], name='seller_docu_uploade_614722_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerdocumentverification',
            index=models.Index(fields=['verified_at'], name='seller_docu_verifie_051810_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerproduct',
            index=models.Index(fields=['is_deleted'], name='seller_prod_is_dele_c307a7_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerproduct',
            index=models.Index(fields=['seller', 'is_deleted'], name='seller_prod_seller__e0194b_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerregistrationrequest',
            index=models.Index(fields=['seller_id', 'status'], name='seller_regi_seller__3289f1_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerregistrationrequest',
            index=models.Index(fields=['reviewed_at'], name='seller_regi_reviewe_2318d8_idx'),
        ),
        migrations.AddIndex(
            model_name='sellersuspension',
            index=models.Index(fields=['seller_id', 'is_active'], name='seller_susp_seller__f4d5e2_idx'),
        ),
        migrations.AddIndex(
            model_name='sellersuspension',
            index=models.Index(fields=['admin_id'], name='seller_susp_admin_i_1f162a_idx'),
        ),
        migrations.AddIndex(
            model_name='sellersuspension',
            index=models.Index(fields=['suspended_until'], name='seller_susp_suspend_dad7b7_idx'),
        ),
        migrations.AddIndex(
            model_name='sellersuspension',
            index=models.Index(fields=['is_active', 'suspended_until'], name='seller_susp_is_acti_1fc60d_idx'),
        ),
        migrations.AddIndex(
            model_name='systemnotification',
            index=models.Index(fields=['recipient_id', 'is_read'], name='system_noti_recipie_cf2f9f_idx'),
        ),
        migrations.AddIndex(
            model_name='systemnotification',
            index=models.Index(fields=['recipient_id', 'created_at'], name='system_noti_recipie_4912fc_idx'),
        ),
        migrations.AddIndex(
            model_name='systemnotification',
            index=models.Index(fields=['is_read', 'created_at'], name='system_noti_is_read_63c326_idx'),
        ),
        migrations.AddIndex(
            model_name='systemnotification',
            index=models.Index(fields=['priority', 'is_read'], name='system_noti_priorit_13e021_idx'),
        ),
        migrations.AddIndex(
            model_name='systemnotification',
            index=models.Index(fields=['related_seller_id'], name='system_noti_related_5a5a2c_idx'),
        ),
        migrations.AddIndex(
            model_name='systemnotification',
            index=models.Index(fields=['related_product_id'], name='system_noti_related_5759a0_idx'),
        ),
        migrations.AddIndex(
            model_name='systemnotification',
            index=models.Index(fields=['notification_type', 'priority'], name='system_noti_notific_eec1d1_idx'),
        ),
        migrations.AddConstraint(
            model_name='pricenoncompliance',
            constraint=models.CheckConstraint(check=models.Q(('listed_price__gt', models.F('ceiling_price'))), name='listed_price_exceeds_ceiling'),
        ),
    ]
