# Generated by Django 4.2.1 on 2025-11-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_pricenoncompliance_pricenoncompliance_listed_price_exceeds_ceiling_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('BUYER', 'Buyer'), ('SELLER', 'Seller'), ('ADMIN', 'Admin')], default='BUYER', help_text='User role: Buyer, Seller, Admin, or System Admin', max_length=20),
        ),
    ]
