# Generated by Django 4.2.1 on 2025-11-23 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerregistrationrequest',
            name='farm_size',
        ),
    ]
