# Generated by Django 4.2.1 on 2025-11-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_sellerregistrationrequest_farm_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_role',
            field=models.CharField(blank=True, choices=[('SUPER_ADMIN', 'Super Admin (Full Access)'), ('SELLER_MANAGER', 'Seller Manager (Approve/Reject Sellers)'), ('PRICE_MANAGER', 'Price Manager (Manage Prices)'), ('ANALYTICS_ADMIN', 'Analytics Admin (View Reports)'), ('SUPPORT_ADMIN', 'Support Admin (Handle Issues)')], default='SUPER_ADMIN', help_text='Permission level for admin users', max_length=20, null=True),
        ),
    ]
