# Generated by Django 4.2.1 on 2025-11-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_add_farm_location'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_email_4b85f2_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_municip_bcc39e_idx',
            old_name='users_munic_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_baranga_badcca_idx',
            old_name='users_baran_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_municip_5839cb_idx',
            old_name='users_munic_baran_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_farm_mu_083ce5_idx',
            old_name='users_farm_munic_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_farm_ba_284d14_idx',
            old_name='users_farm_baran_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_farm_mu_65cfd0_idx',
            old_name='users_farm_munic_baran_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='barangay',
            field=models.CharField(blank=True, help_text='Barangay of residence within the selected municipality', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='municipality',
            field=models.CharField(blank=True, help_text='Municipality of residence (Biliran)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(help_text='Phone number used for authentication', max_length=15, unique=True),
        ),
    ]
