# Generated by Django 4.2.1 on 2025-11-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_add_previous_status_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerproduct',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('EXPIRED', 'Expired'), ('PENDING', 'Pending Approval'), ('REJECTED', 'Rejected')], help_text='Previous status of the product before it was set to EXPIRED', max_length=20, null=True),
        ),
    ]
