# Generated by Django 4.2.1 on 2025-11-27 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_add_product_category_and_category_price_ceiling'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='categorypriceceiling',
            new_name='category_pr_categor_f64a8d_idx',
            old_fields=('category', 'active'),
        ),
        migrations.RemoveField(
            model_name='sellerproduct',
            name='ceiling_price',
        ),
        migrations.AddField(
            model_name='categorypriceceiling',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ceilings_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sellerproduct',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Canonical category/type/subtype node for the product (admin-managed)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='users.productcategory'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['slug'], name='product_cat_slug_801f9e_idx'),
        ),
    ]
