# Generated by Django 4.2.1 on 2025-11-27 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_rename_categorypriceceiling_category_active_category_pr_categor_f64a8d_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sellerproduct',
            name='seller_prod_product_87eea1_idx',
        ),
        migrations.RunSQL(
            "ALTER TABLE seller_products DROP COLUMN IF EXISTS product_type",
            reverse_sql="ALTER TABLE seller_products ADD COLUMN product_type VARCHAR(100)",
        ),
    ]
