# Generated by Django 4.2.1 on 2025-11-29 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_remove_sellerproduct_seller_prod_product_87eea1_idx_and_more'),
    ]

    operations = [
    ]
