# Generated by Django 4.2.1 on 2025-11-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_merge_20251129_1700'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sellerorder',
            index=models.Index(fields=['product', 'status'], name='seller_orde_product_ef9d3a_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerorder',
            index=models.Index(fields=['product', 'buyer'], name='seller_orde_product_ac2096_idx'),
        ),
    ]
