# Generated by Django 4.2.1 on 2025-12-01 01:08

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_remove_sellerproduct_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerproduct',
            name='baseline_stock',
            field=models.IntegerField(default=0, help_text='Current baseline stock for percentage calculation (updates on restock)'),
        ),
        migrations.AddField(
            model_name='sellerproduct',
            name='initial_stock',
            field=models.IntegerField(default=0, help_text='Original stock amount when product was first created (for analytics)'),
        ),
        migrations.AddField(
            model_name='sellerproduct',
            name='stock_baseline_updated_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now, help_text='Timestamp when baseline stock was last updated (on restock)'),
            preserve_default=False,
        ),
    ]
