# Generated by Django 4.2.1 on 2025-12-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_remove_sellerproduct_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerproduct',
            name='fulfillment_methods',
            field=models.CharField(choices=[('delivery', 'Delivery Only'), ('pickup', 'Pickup Only'), ('delivery_and_pickup', 'Delivery & Pickup')], default='delivery_and_pickup', help_text='Fulfillment methods available for this product', max_length=50),
        ),
    ]
