# Generated by Django 4.2.1 on 2025-12-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_add_is_opas_managed'),
    ]

    operations = [
        migrations.CreateModel(
            name='OPASProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique product name from CSV', max_length=255, unique=True)),
                ('category_forecast', models.CharField(blank=True, help_text='Category (VEGETABLE, FRUIT, LIVESTOCK, POULTRY, SEEDS, FERTILIZERS, FEEDS, MEDICINES)', max_length=100, null=True)),
                ('product_type', models.CharField(blank=True, help_text='Type in English (e.g., Banana, Tomato, Chicken)', max_length=100, null=True)),
                ('product_subtype', models.CharField(blank=True, help_text='Subtype in original language (e.g., Lakatan, Fresh, Lechonon)', max_length=100, null=True)),
                ('forecast_group_key', models.CharField(blank=True, help_text='Composite key: category:type:subtype for grouping with similar products', max_length=300)),
                ('is_active', models.BooleanField(default=True, help_text='Active for forecasting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imported_from_csv', models.DateTimeField(blank=True, help_text='When product was imported from CSV', null=True)),
            ],
            options={
                'verbose_name': 'OPAS Product',
                'verbose_name_plural': 'OPAS Products',
                'db_table': 'opas_products',
            },
        ),
        migrations.AddIndex(
            model_name='opasproduct',
            index=models.Index(fields=['name'], name='opas_product_name_idx'),
        ),
        migrations.AddIndex(
            model_name='opasproduct',
            index=models.Index(fields=['category_forecast', 'product_type', 'product_subtype'], name='opas_product_class_idx'),
        ),
        migrations.AddIndex(
            model_name='opasproduct',
            index=models.Index(fields=['forecast_group_key'], name='opas_product_group_idx'),
        ),
        migrations.RemoveIndex(
            model_name='sellerproduct',
            name='is_opas_managed_idx',
        ),
        migrations.RenameIndex(
            model_name='sellerproduct',
            new_name='seller_prod_categor_b4dda6_idx',
            old_name='seller_prod_categor_idx',
        ),
        migrations.RenameIndex(
            model_name='sellerproduct',
            new_name='seller_prod_is_dele_b3027b_idx',
            old_name='seller_prod_status_idx',
        ),
        migrations.AlterField(
            model_name='sellerproduct',
            name='category_forecast',
            field=models.CharField(blank=True, help_text='Forecasting category (e.g., VEGETABLES, LIVESTOCK, FRUITS)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sellerproduct',
            name='product_subtype',
            field=models.CharField(blank=True, help_text='Specific product subtype (e.g., Bangus, Chicken, Tomato)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sellerproduct',
            name='product_type',
            field=models.CharField(blank=True, help_text='Product type within category (e.g., Fish, Poultry, Leafy Vegetables)', max_length=100, null=True),
        ),
    ]
