# Generated by Django 4.2.1 on 2025-12-08 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_sellerproduct_opas_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Proof image of delivery', upload_to='opas_delivery_proofs/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When the proof was uploaded')),
            ],
            options={
                'verbose_name': 'Delivery Proof',
                'verbose_name_plural': 'Delivery Proofs',
                'db_table': 'delivery_proofs',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='opasproduct',
            new_name='opas_produc_name_41e47d_idx',
            old_name='opas_product_name_idx',
        ),
        migrations.RenameIndex(
            model_name='opasproduct',
            new_name='opas_produc_categor_414380_idx',
            old_name='opas_product_class_idx',
        ),
        migrations.RenameIndex(
            model_name='opasproduct',
            new_name='opas_produc_forecas_b28b69_idx',
            old_name='opas_product_group_idx',
        ),
        migrations.RenameIndex(
            model_name='opasproductsale',
            new_name='opas_produc_opas_pr_260f6f_idx',
            old_name='opas_prod_opas_pr_idx',
        ),
        migrations.RenameIndex(
            model_name='opasproductsale',
            new_name='opas_produc_sale_da_871a38_idx',
            old_name='opas_prod_sale_date_idx',
        ),
        migrations.AddField(
            model_name='deliveryproof',
            name='submission',
            field=models.ForeignKey(help_text='The OPAS submission this proof is for', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_proof_images', to='users.selltoopas'),
        ),
        migrations.AddField(
            model_name='deliveryproof',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='Admin who uploaded this proof', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_delivery_proofs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='deliveryproof',
            index=models.Index(fields=['submission', '-uploaded_at'], name='delivery_pr_submiss_729ad4_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryproof',
            index=models.Index(fields=['uploaded_by'], name='delivery_pr_uploade_37cef6_idx'),
        ),
    ]
