# Generated by Django 4.2.1 on 2025-12-09 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_deliveryproof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opaspurchaseorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('DELIVERED', 'Delivered'), ('REJECTED', 'Rejected'), ('PARTIALLY_APPROVED', 'Partially Approved'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Review status of OPAS submission', max_length=25),
        ),
    ]
