# Generated by Django 4.2.1 on 2025-12-09 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_alter_opaspurchaseorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='opaspurchaseorder',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='When delivery proof was submitted', null=True),
        ),
        migrations.AddIndex(
            model_name='opaspurchaseorder',
            index=models.Index(fields=['delivered_at'], name='opas_purcha_deliver_abb15c_idx'),
        ),
    ]
