# Generated by Django 4.2.1 on 2025-12-03 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0030_add_fulfillment_methods_to_sellerproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateTimeField(auto_now_add=True, help_text='When this forecast was generated')),
                ('forecast_period', models.CharField(help_text='Period being forecasted (e.g., "2025-01", "Week 1 2025")', max_length=20)),
                ('is_current', models.BooleanField(db_index=True, default=True, help_text='Is this the latest forecast for this product?')),
                ('demand_forecast_kg', models.DecimalField(decimal_places=2, help_text='Predicted demand in kilograms', max_digits=12)),
                ('demand_lower_bound', models.DecimalField(decimal_places=2, help_text='Lower bound of 95% confidence interval for demand', max_digits=12)),
                ('demand_upper_bound', models.DecimalField(decimal_places=2, help_text='Upper bound of 95% confidence interval for demand', max_digits=12)),
                ('price_forecast', models.DecimalField(decimal_places=2, help_text='Predicted price per kilogram', max_digits=10)),
                ('price_lower_bound', models.DecimalField(decimal_places=2, help_text='Lower bound of 95% confidence interval for price', max_digits=10)),
                ('price_upper_bound', models.DecimalField(decimal_places=2, help_text='Upper bound of 95% confidence interval for price', max_digits=10)),
                ('model_type', models.CharField(choices=[('SARIMA', 'SARIMA (Seasonal ARIMA)'), ('ARIMA', 'ARIMA (Non-Seasonal)'), ('SIMPLE', 'Simple (Exponential Smoothing)'), ('INSUFFICIENT_DATA', 'Insufficient Data')], default='INSUFFICIENT_DATA', help_text='Type of forecasting model used', max_length=20)),
                ('confidence_level', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='LOW', help_text='Confidence level of forecast based on data quality', max_length=10)),
                ('rmse_demand', models.DecimalField(blank=True, decimal_places=4, help_text='Root Mean Square Error for demand model', max_digits=10, null=True)),
                ('rmse_price', models.DecimalField(blank=True, decimal_places=4, help_text='Root Mean Square Error for price model', max_digits=10, null=True)),
                ('mape_demand', models.DecimalField(blank=True, decimal_places=2, help_text='Mean Absolute Percentage Error for demand (percentage)', max_digits=5, null=True)),
                ('mape_price', models.DecimalField(blank=True, decimal_places=2, help_text='Mean Absolute Percentage Error for price (percentage)', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='The product being forecasted', on_delete=django.db.models.deletion.CASCADE, related_name='admin_forecasts', to='users.sellerproduct')),
            ],
            options={
                'verbose_name': 'Product Forecast',
                'verbose_name_plural': 'Product Forecasts',
                'db_table': 'forecasting_product_forecast',
                'ordering': ['-forecast_date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(help_text='Date of the transaction/aggregation period')),
                ('quantity_sold_kg', models.DecimalField(decimal_places=2, default=0, help_text='Total quantity sold in this period', max_digits=12)),
                ('average_price_per_kg', models.DecimalField(decimal_places=2, default=0, help_text='Average selling price per kilogram in this period', max_digits=10)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, help_text='Total revenue (quantity × average price)', max_digits=15)),
                ('transaction_count', models.IntegerField(default=0, help_text='Number of individual transactions in this period')),
                ('data_quality_score', models.IntegerField(default=100, help_text='Quality score 0-100 (100 = complete data, 0 = missing/suspect data)')),
                ('is_complete', models.BooleanField(default=True, help_text='Whether this period has complete data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='The product these transactions relate to', on_delete=django.db.models.deletion.CASCADE, related_name='historical_transactions', to='users.sellerproduct')),
            ],
            options={
                'verbose_name': 'Historical Transaction',
                'verbose_name_plural': 'Historical Transactions',
                'db_table': 'forecasting_historical_transactions',
                'ordering': ['product', 'transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='ForecastMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('SARIMA', 'SARIMA (Seasonal ARIMA)'), ('ARIMA', 'ARIMA (Non-Seasonal)'), ('SIMPLE', 'Simple (Exponential Smoothing)'), ('INSUFFICIENT_DATA', 'Insufficient Data')], default='INSUFFICIENT_DATA', help_text='Type of forecasting model selected for this product', max_length=20)),
                ('data_points_count', models.IntegerField(default=0, help_text='Number of historical data points available')),
                ('data_coverage_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Percentage of expected time periods with data (0-100)', max_digits=5)),
                ('is_reliable', models.BooleanField(db_index=True, default=False, help_text='Whether forecast is reliable (enough data quality)')),
                ('model_parameters', models.JSONField(blank=True, default=dict, help_text='Stores SARIMA/ARIMA parameters: {order: (p,d,q), seasonal_order: (P,D,Q,m)}')),
                ('last_training_date', models.DateTimeField(blank=True, help_text='When the model was last trained', null=True)),
                ('last_successful_forecast_date', models.DateTimeField(blank=True, help_text='When forecast was last successfully generated', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about model limitations or issues')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(help_text='The product this metadata belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='forecast_metadata', to='users.sellerproduct')),
            ],
            options={
                'verbose_name': 'Forecast Metadata',
                'verbose_name_plural': 'Forecast Metadata',
                'db_table': 'forecasting_forecast_metadata',
            },
        ),
        migrations.CreateModel(
            name='ForecastAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('DECLINING_DEMAND', 'Declining Demand'), ('PRICE_SPIKE', 'Price Spike'), ('LOW_CONFIDENCE', 'Low Confidence Forecast'), ('ANOMALY', 'Data Anomaly'), ('MODEL_FAILURE', 'Model Training Failure')], help_text='Type of alert', max_length=30)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='WARNING', help_text='Alert severity level', max_length=10)),
                ('message', models.TextField(help_text='Detailed description of the alert')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional structured data about the alert')),
                ('is_acknowledged', models.BooleanField(db_index=True, default=False, help_text='Whether admin has acknowledged this alert')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, help_text='When the alert was acknowledged', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the alert was resolved', null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, help_text='Admin who acknowledged this alert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_forecast_alerts', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(help_text='The product this alert relates to', on_delete=django.db.models.deletion.CASCADE, related_name='forecast_alerts', to='users.sellerproduct')),
                ('related_forecast', models.ForeignKey(blank=True, help_text='Related forecast that triggered this alert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='forecasting.productforecast')),
            ],
            options={
                'verbose_name': 'Forecast Alert',
                'verbose_name_plural': 'Forecast Alerts',
                'db_table': 'forecasting_forecast_alert',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='productforecast',
            index=models.Index(fields=['product', '-forecast_date'], name='forecasting_product_1e2e28_idx'),
        ),
        migrations.AddIndex(
            model_name='productforecast',
            index=models.Index(fields=['product', 'is_current'], name='forecasting_product_463c19_idx'),
        ),
        migrations.AddIndex(
            model_name='productforecast',
            index=models.Index(fields=['model_type'], name='forecasting_model_t_25c47e_idx'),
        ),
        migrations.AddIndex(
            model_name='productforecast',
            index=models.Index(fields=['confidence_level'], name='forecasting_confide_18c055_idx'),
        ),
        migrations.AddConstraint(
            model_name='productforecast',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('product', 'forecast_period'), name='unique_current_forecast_per_product_period'),
        ),
        migrations.AddIndex(
            model_name='historicaltransactions',
            index=models.Index(fields=['product', 'transaction_date'], name='forecasting_product_11420a_idx'),
        ),
        migrations.AddIndex(
            model_name='historicaltransactions',
            index=models.Index(fields=['product', '-transaction_date'], name='forecasting_product_287a8e_idx'),
        ),
        migrations.AddIndex(
            model_name='historicaltransactions',
            index=models.Index(fields=['transaction_date'], name='forecasting_transac_95096e_idx'),
        ),
        migrations.AddConstraint(
            model_name='historicaltransactions',
            constraint=models.UniqueConstraint(fields=('product', 'transaction_date'), name='unique_product_transaction_date'),
        ),
        migrations.AddIndex(
            model_name='forecastmetadata',
            index=models.Index(fields=['model_type', 'is_reliable'], name='forecasting_model_t_477606_idx'),
        ),
        migrations.AddIndex(
            model_name='forecastalert',
            index=models.Index(fields=['product', '-created_at'], name='forecasting_product_0fd0a3_idx'),
        ),
        migrations.AddIndex(
            model_name='forecastalert',
            index=models.Index(fields=['alert_type', 'is_acknowledged'], name='forecasting_alert_t_12d3e2_idx'),
        ),
        migrations.AddIndex(
            model_name='forecastalert',
            index=models.Index(fields=['severity', '-created_at'], name='forecasting_severit_69f683_idx'),
        ),
    ]
