# Generated by Django 4.2.1 on 2025-12-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketHistoricalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Name of the product (not necessarily in SellerProduct table)', max_length=255)),
                ('category_name', models.CharField(blank=True, help_text='Product category from external source', max_length=255)),
                ('market_date', models.DateField(help_text='Date of the market data')),
                ('quantity_kg', models.DecimalField(decimal_places=2, default=0, help_text='Quantity traded in the market for this period', max_digits=12)),
                ('price_per_kg', models.DecimalField(decimal_places=2, default=0, help_text='Average market price per kilogram', max_digits=10)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, help_text='Total market value (quantity × price)', max_digits=15)),
                ('source', models.CharField(default='CSV Import', help_text='Source of this data (e.g., "CSV Import", "Market Bureau", "Agricultural Bureau")', max_length=255)),
                ('data_quality_score', models.IntegerField(default=100, help_text='Quality score 0-100 (100 = complete/verified data)')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this market data entry')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Market Historical Data',
                'verbose_name_plural': 'Market Historical Data',
                'db_table': 'forecasting_market_historical_data',
                'ordering': ['product_name', 'market_date'],
                'indexes': [models.Index(fields=['product_name', 'market_date'], name='forecasting_product_66104e_idx'), models.Index(fields=['market_date'], name='forecasting_market__dbc5ec_idx'), models.Index(fields=['source'], name='forecasting_source_c6911b_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='markethistoricaldata',
            constraint=models.UniqueConstraint(fields=('product_name', 'market_date', 'source'), name='unique_market_product_date_source'),
        ),
    ]
