# Generated by Django 4.2.1 on 2025-12-04 02:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0002_markethistoricaldata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productforecast',
            name='product_name',
            field=models.CharField(blank=True, default='', help_text='Product name (for CSV/market data forecasts)', max_length=255),
        ),
        migrations.AlterField(
            model_name='productforecast',
            name='forecast_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this forecast was generated'),
        ),
        migrations.AlterField(
            model_name='productforecast',
            name='product',
            field=models.ForeignKey(blank=True, help_text='The product being forecasted (farmer product)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_forecasts', to='users.sellerproduct'),
        ),
    ]
