/// Location data model for Biliran municipalities and barangays
class LocationData {
  static const Map<String, List<String>> municipalityBarangays = {
    'Almeria': [
      'Caucab',
      'Iyosan',
      'Jamorawon',
      'Lo-ok',
      'Matanggo',
      'Pili',
      'Poblacion',
      'Pulangbato',
      'Salangi',
      'Sampao',
      'Tabunan',
      'Talahid',
      'Tamarindo',
    ],
    'Biliran': [
      'Bato',
      'Burabod',
      'Busali',
      'Canila',
      'Hugpa',
      'Julita',
      'Pinangomhan',
      'San Isidro',
      'San Roque',
      'Sanggalang',
      'Villa Enage',
    ],
    'Cabucgayan': [
      'Balaquid',
      'Baso',
      'Bunga',
      'Caanibongan',
      'Casiawan',
      'Esperanza',
      'Langgao',
      'Libertad',
      'Looc',
      'Magbangon',
      'Pawikan',
      'Salawad',
      'Talibong',
    ],
    'Caibiran': [
      'Alegria',
      'Asug',
      'Bariis',
      'Binohangan',
      'Cabibihan',
      'Kaulangohan',
      'Kawayanon',
      'Looc',
      'Manlabang',
      'Maurang',
      'Palanay',
      'Palengke',
      'Tomalistis',
      'Union',
      'Uson',
      'Victory',
      'Villa Vicenta',
    ],
    'Culaba': [
      'Acaban',
      'Bacolod',
      'Binongtoan',
      'Bool Central',
      'Bool East',
      'Bool West',
      'Culaba Central',
      'Guindapunan',
      'Habuhab',
      'Kalipayan',
      'Looc',
      'Marvel',
      'Patag',
      'Pinamihagan',
      'Salvacion',
      'San Roque',
      'Virginia',
    ],
    'Kawayan': [
      'Baganito',
      'Balacson',
      'Balite',
      'Bilwang',
      'Bulalacao',
      'Burabod',
      'Buyo',
      'Inasuyan',
      'Kansanok',
      'Villa Cornejo (Looc)',
      'Madao',
      'Mapuyo',
      'Masagaosao',
      'Masagongsong',
      'Poblacion',
      'San Lorenzo',
      'Tabunan North',
      'Tubig Guinoo',
      'Tucdao',
      'Ungale',
    ],
    'Maripipi': [
      'Agutay',
      'Banlas',
      'Bato',
      'Binalayan East',
      'Binalayan West',
      'Binongtoan',
      'Burabod',
      'Calbani',
      'Canduhao',
      'Casibang',
      'Danao',
      'Ermita',
      'Ol-og',
      'Trabugan',
      'Viga',
    ],
    'Naval': [
      'Agpangi',
      'Anislagan',
      'Atipolo',
      'Borac',
      'Cabungaan',
      'Calumpang',
      'Capinahan',
      'Caraycaray',
      'Catmon',
      'Haguikhikan',
      'Imelda',
      'Larrazabal',
      'Libertad',
      'Libtong',
      'Lico',
      'Lucso-on',
      'Mabini',
      'Padre Sergio Eamiguel',
      'Padre Inocentes Garcia',
      'Sabang',
      'San Pablo',
      'Santo Nino',
      'Santissimo Rosario',
      'Villa Caneja',
      'Villa Consuelo',
    ],
  };

  /// Get all municipalities sorted alphabetically
  static List<String> get municipalities => municipalityBarangays.keys.toList()..sort();

  /// Get barangays for a specific municipality
  static List<String> getBarangays(String municipality) {
    return municipalityBarangays[municipality] ?? [];
  }
}
